### ISSUE TITLE
Project architecture

### ISSUE THREAD

**Issue by x100dev** [Alireza-Razavi/SimpleJavaChat#3]
Hello, is it possible to run this project on different computers?

**Comment by Alireza-Razavi** [comment]
@x100dev Hello.
The simple answer is yes.
But you should note that all computers are in a shared network and currently each client can only connect to 1 another client (because the IP address of target client is hard coded in source code as i have mentioned in README)
The implementation could be something like this:
1. Run the server in computer `A`
2. Fix the IP address of the server computer in client app's source code, it must be the same for all clients (i have mentioned the code line in README)
3. Run first client in computer `B`
4. Run second client in computer `C`
5. Fix IP address of `B` for client `C` and vice versa.
